language: python

python:
  - "3.6.9"
  - "3.7"
  - "3.9"

install:
  - pip install -r requirements-dev.txt
  - pip install codecov
  - pip install flake8
  - echo 'from .defaults import *' > crowdclick/settings/local.py
  - mkdir -p assets/task_image
  - echo 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAAAAAA6fptVAAAACklEQVR4nGP6DwABBQECz6AuzQAAAABJRU5ErkJggg==' | base64 -d > assets/task_image/placeholder.png

script:
  - coverage run manage.py test
  - coverage report
  - flake8 .

after_success:
  - codecov
